remote_theme: daattali/beautiful-jekyll
plugins:
 - jekyll-remote-theme 

title: Nicholas Bailey
description: 

show_downloads: false

include: ["_posts"]

defaults:
  - mathjax: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      social-share: true # add social media sharing buttons to all blog posts
      mathjax: true
  -
    scope:
      path: "" 
    values:
      mathjax: true

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  ITAC Training:
    - Introduction: "/itac-training/"
    - Utility Analysis: "/itac-training/utility-analysis/"
    - Motors: "/itac-training/motors/"
    - Compressed Air: "/itac-training/compressed-air/"
    - Cooling Systems: "/itac-training/cooling/"
    - Boilers: "/itac-training/boilers/"
    - HVAC: "/itac-training/hvac/"
    - LaTeX: "/itac-training/LaTeX/"
