remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
 - jekyll-remote-theme 

title: Nicholas Bailey
description: 

show_downloads: false

include: ["_posts"]
include: ["itac-training"]
