remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
 - jekyll-remote-theme 

title: Nicholas Bailey
description: 

show_downloads: false

include: ["_posts"]

mathjax: true

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  ITAC Training:
    - Introduction: "/itac-training/"
    - Utility Analysis: "/itac-training/utility-analysis/"
    - Compressed Air: "/itac-training/compressed-air/"

